import { ArrowUpRight, Check, ChevronRight, CircleAlert, Clock3, Filter, RotateCcw, Search, X } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { useMemo, type ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useSifData } from "@/lib/sif-context";
import { sites, activities, lifeSavingRules, type RiskLevel, type SafetyReport } from "@/lib/sif-data";
import { cn } from "@/lib/utils";

export function riskTone(level: RiskLevel | string) {
  return level === "CRITICAL" ? "bg-critical/10 text-critical ring-critical/20" : level === "HIGH" ? "bg-high/10 text-high ring-high/20" : level === "MEDIUM" ? "bg-medium/15 text-ink ring-medium/30" : "bg-low/10 text-low ring-low/20";
}

export function RiskBadge({ level }: { level: RiskLevel }) { return <Badge className={cn("rounded-full border-0 px-2 py-1 text-[10px] font-semibold tracking-wide ring-1", riskTone(level))}>{level}</Badge>; }
export function ClassificationBadge({ classification }: { classification: SafetyReport["ai"]["classification"] }) { return <Badge className={cn("rounded-full border-0 px-2 py-1 text-[10px] font-semibold tracking-wide ring-1", classification === "SIF_POTENTIAL" ? "bg-critical/10 text-critical ring-critical/20" : "bg-low/10 text-low ring-low/20")}>{classification === "SIF_POTENTIAL" ? "SIF POTENTIAL" : "NON-SIF"}</Badge>; }
export function ReviewBadge({ status }: { status: SafetyReport["review_status"] }) { return <Badge className={cn("rounded-full border-0 px-2 py-1 text-[10px] font-semibold tracking-wide ring-1", status === "REVIEW_REQUIRED" ? "bg-medium/15 text-ink ring-medium/30" : status === "CONFIRMED_SIF" ? "bg-critical/10 text-critical ring-critical/20" : "bg-low/10 text-low ring-low/20")}>{status === "REVIEW_REQUIRED" ? "REVIEW REQUIRED" : status === "CONFIRMED_SIF" ? "CONFIRMED SIF" : "MARKED NON-SIF"}</Badge>; }

export function FilterStrip() {
  const { filters, setFilter, resetFilters } = useSifData();
  const selectClass = "h-8 rounded-lg border-0 bg-background/75 px-3 text-xs font-medium text-ink/70 ring-1 ring-ink/10 outline-none focus:ring-2 focus:ring-ring";
  return <div className="mb-6 flex flex-wrap items-center gap-2 border-b border-ink/10 pb-4"><div className="mr-1 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-wide text-ink/40"><Filter className="size-3.5" />Filter</div><select className={selectClass} value={filters.site} onChange={(event) => setFilter("site", event.target.value)}><option>All</option>{sites.map((site) => <option key={site}>{site}</option>)}</select><select className={selectClass} value={filters.activity} onChange={(event) => setFilter("activity", event.target.value)}><option>All</option>{activities.map((activity) => <option key={activity}>{activity}</option>)}</select><select className={selectClass} value={filters.rule} onChange={(event) => setFilter("rule", event.target.value)}><option>All</option>{lifeSavingRules.map((rule) => <option key={rule}>{rule}</option>)}</select><select className={selectClass} value={filters.risk} onChange={(event) => setFilter("risk", event.target.value)}><option>All</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><select className={selectClass} value={filters.classification} onChange={(event) => setFilter("classification", event.target.value)}><option>All</option><option>SIF_POTENTIAL</option><option>NON_SIF</option></select><Button variant="ghost" size="sm" className="ml-auto text-ink/45" onClick={resetFilters}><RotateCcw className="size-3.5" />Reset filters</Button></div>;
}

export function useFilteredReports() {
  const { reports, filters } = useSifData();
  return useMemo(() => reports.filter((report) => {
    const search = filters.search.toLowerCase();
    return (filters.site === "All" || report.site === filters.site) && (filters.activity === "All" || report.activity === filters.activity) && (filters.rule === "All" || report.ai.life_saving_rules.includes(filters.rule)) && (filters.risk === "All" || report.ai.risk_level === filters.risk) && (filters.classification === "All" || report.ai.classification === filters.classification) && (!search || `${report.id} ${report.description} ${report.site} ${report.activity}`.toLowerCase().includes(search));
  }), [reports, filters]);
}

export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-ink/15 bg-background/40 p-10 text-center"><CircleAlert className="mx-auto size-7 text-ink/25" /><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-1 text-sm text-ink/50">{description}</p></div>; }

export function ReportTable({ reports, compact = false }: { reports: SafetyReport[]; compact?: boolean }) {
  return <div className="overflow-x-auto rounded-2xl bg-background/65 ring-1 ring-ink/10"><table className="w-full min-w-[920px] text-left text-xs"><thead className="border-b border-ink/10 text-[10px] uppercase tracking-[0.14em] text-ink/40"><tr>{["Report ID", "Date", "Site", "Type", "Activity", "Description", "SIF Score", "Classification", "Review"].map((head) => <th key={head} className="px-4 py-3 font-semibold">{head}</th>)}</tr></thead><tbody className="divide-y divide-ink/10">{reports.map((report) => <tr key={report.id} className="group transition-colors hover:bg-navy/5"><td className="px-4 py-3"><Link to="/reports/$reportId" params={{ reportId: report.id }} className="font-semibold text-navy hover:text-amber">{report.id}</Link></td><td className="whitespace-nowrap px-4 py-3 text-ink/55">{report.date}</td><td className="px-4 py-3 font-medium">{report.site}</td><td className="px-4 py-3 text-ink/55">{report.report_type}</td><td className="px-4 py-3 text-ink/65">{report.activity}</td><td className="max-w-[280px] px-4 py-3 text-ink/60"><Link to="/reports/$reportId" params={{ reportId: report.id }} className="line-clamp-2 hover:text-ink">{report.description}</Link></td><td className="px-4 py-3"><span className={cn("font-display text-lg font-semibold", report.ai.risk_level === "CRITICAL" ? "text-critical" : report.ai.risk_level === "HIGH" ? "text-high" : "text-ink")}>{report.ai.sif_score}</span></td><td className="px-4 py-3"><ClassificationBadge classification={report.ai.classification} /></td><td className="px-4 py-3"><ReviewBadge status={report.review_status} /></td></tr>)}</tbody></table>{reports.length === 0 && <EmptyState title="No reports match these filters" description="Reset the filters or broaden the search to continue reviewing reports." />}</div>;
}

export function ScoreBar({ score }: { score: number }) { return <div className="flex items-center gap-2"><div className="h-2 w-20 overflow-hidden rounded-full bg-ink/10"><div className={cn("h-full rounded-full", score >= 80 ? "bg-critical" : score >= 60 ? "bg-high" : score >= 30 ? "bg-medium" : "bg-low")} style={{ width: `${score}%` }} /></div><span className="w-7 text-right text-[11px] font-semibold tabular-nums">{score}</span></div>; }

export function Donut({ reports }: { reports: SafetyReport[] }) { const counts = { CRITICAL: reports.filter((r) => r.ai.risk_level === "CRITICAL").length, HIGH: reports.filter((r) => r.ai.risk_level === "HIGH").length, MEDIUM: reports.filter((r) => r.ai.risk_level === "MEDIUM").length, LOW: reports.filter((r) => r.ai.risk_level === "LOW").length }; const total = Math.max(reports.length, 1); const c1 = (counts.CRITICAL / total) * 100; const c2 = c1 + (counts.HIGH / total) * 100; const c3 = c2 + (counts.MEDIUM / total) * 100; return <div className="relative size-36 shrink-0 rounded-full" style={{ background: `conic-gradient(var(--critical) 0 ${c1}%, var(--high) ${c1}% ${c2}%, var(--medium) ${c2}% ${c3}%, var(--low) ${c3}% 100%)` }}><div className="absolute inset-[22%] grid place-items-center rounded-full bg-paper/95 text-center"><div><div className="font-display text-2xl font-semibold tabular-nums">{reports.length}</div><div className="text-[9px] uppercase tracking-wide text-ink/40">reports</div></div></div></div>; }

export function MetricCard({ label, value, detail, tone = "default", icon: Icon }: { label: string; value: string | number; detail: string; tone?: "default" | "critical" | "medium" | "low"; icon?: typeof ArrowUpRight }) { return <div className={cn("rounded-2xl bg-background/65 p-4 ring-1 ring-ink/10 animate-settle", tone === "critical" && "bg-critical/8 ring-critical/20", tone === "medium" && "bg-medium/10 ring-medium/30", tone === "low" && "bg-low/8 ring-low/20")}><div className="flex items-center justify-between"><div className="text-[11px] font-medium text-ink/45">{label}</div>{Icon && <Icon className="size-4 text-ink/30" />}</div><div className={cn("mt-2 font-display text-3xl font-semibold tracking-tight tabular-nums", tone === "critical" ? "text-critical" : tone === "medium" ? "text-ink" : tone === "low" ? "text-low" : "text-ink")}>{value}</div><div className="mt-1 text-[11px] text-ink/45">{detail}</div></div>; }

export function SearchField({ value, onChange, placeholder = "Search reports…" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="flex h-9 min-w-[220px] flex-1 items-center gap-2 rounded-lg bg-background/75 px-3 ring-1 ring-ink/10"><Search className="size-4 text-ink/35" /><Input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="h-auto border-0 bg-transparent p-0 text-xs shadow-none focus-visible:ring-0" /></div>; }

export function KeyValue({ label, children }: { label: string; children: ReactNode }) { return <div className="flex gap-3 border-b border-ink/10 py-3 text-sm"><span className="w-32 shrink-0 text-ink/45">{label}</span><span className="font-medium text-ink/75">{children}</span></div>; }

export function StepLine({ number, title, detail, active = false }: { number: string; title: string; detail: string; active?: boolean }) { return <div className="flex gap-3"><div className={cn("grid size-7 shrink-0 place-items-center rounded-full text-xs font-semibold ring-1", active ? "bg-amber text-ink ring-amber/40" : "bg-navy/5 text-navy ring-navy/15")}>{number}</div><div><div className="text-sm font-semibold">{title}</div><div className="mt-1 text-xs text-ink/50">{detail}</div></div></div>; }

export function BackLink({ to, children = "Back" }: { to: "/reports" | "/"; children?: ReactNode }) { return <Link to={to} className="mb-4 inline-flex items-center gap-1 text-xs font-semibold text-ink/50 hover:text-ink"><ChevronRight className="size-3 rotate-180" />{children}</Link>; }