/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analyze': typeof AnalyzeRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analyze': typeof AnalyzeRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analyze': typeof AnalyzeRoute
  '/login': typeof LoginRoute
  '/patterns': typeof PatternsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/review': typeof ReviewRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analyze'
    | '/login'
    | '/patterns'
    | '/reports'
    | '/review'
    | '/rules'
    | '/settings'
    | '/sites'
    | '/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analyze'
    | '/login'
    | '/patterns'
    | '/reports'
    | '/review'
    | '/rules'
    | '/settings'
    | '/sites'
    | '/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analyze'
    | '/login'
    | '/patterns'
    | '/reports'
    | '/review'
    | '/rules'
    | '/settings'
    | '/sites'
    | '/reports/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyzeRoute: typeof AnalyzeRoute
  LoginRoute: typeof LoginRoute
  PatternsRoute: typeof PatternsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsReportIdRoute: typeof ReportsReportIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsReportIdRoute: ReportsReportIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyzeRoute: AnalyzeRoute,
  LoginRoute: LoginRoute,
  PatternsRoute: PatternsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ReviewRoute: ReviewRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
